# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Acl名称')),
                ('criterion', models.CharField(max_length=255, verbose_name='acl规则')),
                ('criterion_args', models.CharField(blank=True, max_length=255, null=True, verbose_name='acl规则参数')),
                ('flags', models.CharField(max_length=255, verbose_name='acl flags')),
                ('value', models.CharField(max_length=255, verbose_name='acl value')),
            ],
            options={
                'verbose_name': 'acl配置',
                'verbose_name_plural': 'acl配置',
            },
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='frontend名称')),
                ('ip', models.CharField(max_length=255, verbose_name='监听地址')),
                ('port', models.CharField(max_length=255, verbose_name='端口')),
                ('mode', models.CharField(max_length=255, verbose_name='模式')),
                ('monitor_uri', models.CharField(max_length=255, verbose_name='监测地址')),
            ],
            options={
                'verbose_name': 'frontend全局配置',
                'verbose_name_plural': 'frontend全局配置',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='实例名称')),
                ('ip', models.CharField(max_length=255, verbose_name='IP地址')),
                ('ha_version', models.CharField(max_length=255, verbose_name='haproxy版本')),
                ('cluster', models.CharField(max_length=255, verbose_name='所属集群')),
            ],
            options={
                'verbose_name': 'haproxy实例',
                'verbose_name_plural': 'haproxy实例',
            },
        ),
        migrations.AddField(
            model_name='frontend',
            name='instance',
            field=models.ManyToManyField(db_constraint=False, to='haproxy.Instance'),
        ),
        migrations.AddField(
            model_name='acl',
            name='frontend',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='haproxy.Frontend'),
        ),
    ]
