# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-21 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='flags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='acl flags'),
        ),
    ]
