# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0002_auto_20190121_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='beckend名称')),
            ],
            options={
                'verbose_name': 'Backend',
                'verbose_name_plural': 'Backend',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='server名称')),
                ('ip', models.CharField(max_length=255, verbose_name='server ip')),
                ('port', models.CharField(max_length=255, verbose_name='server端口')),
                ('check_interal', models.CharField(max_length=255, verbose_name='检测间隔')),
                ('rise', models.CharField(max_length=255, verbose_name='正常检测次数')),
                ('fall', models.CharField(max_length=255, verbose_name='失败检测次数')),
                ('cookie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie值')),
                ('backend', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='haproxy.Backend')),
            ],
            options={
                'verbose_name': 'server信息',
                'verbose_name_plural': 'server信息',
            },
        ),
    ]
