# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-21 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0003_backend_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='check_interal',
            new_name='check_interval',
        ),
    ]
