# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0004_auto_20190121_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='权重'),
        ),
    ]
