# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0005_server_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='option选项')),
                ('param', models.CharField(blank=True, max_length=255, null=True, verbose_name='option参数')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'option',
            },
        ),
        migrations.AddField(
            model_name='backend',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='balance规则'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(max_length=255, verbose_name='backend名称'),
        ),
        migrations.AddField(
            model_name='option',
            name='backend',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='haproxy.Backend'),
        ),
        migrations.AddField(
            model_name='option',
            name='frontend',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='haproxy.Frontend'),
        ),
    ]
