# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0007_auto_20190122_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='instance',
            field=models.ManyToManyField(db_constraint=False, to='haproxy.Instance'),
        ),
    ]
