# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0008_backend_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='haproxy.Backend')),
            ],
        ),
        migrations.AddField(
            model_name='acl',
            name='use_backend',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='haproxy.UseBackend'),
        ),
    ]
