# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-23 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0010_auto_20190123_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usebackend',
            name='backend',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='backend_name', related_query_name='backend_name', to='haproxy.Backend'),
        ),
    ]
