# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-23 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0011_auto_20190123_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acl',
            name='use_backend',
        ),
    ]
