# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0012_remove_acl_use_backend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usebackend',
            options={'verbose_name': 'UseBackend', 'verbose_name_plural': 'UseBackend'},
        ),
        migrations.AddField(
            model_name='usebackend',
            name='acl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acl规则'),
        ),
    ]
