# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haproxy', '0013_auto_20190123_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usebackend',
            name='backend',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='haproxy.Backend'),
        ),
    ]
